# Uses rustfmt features only available with nightly rust.
# If you have nightly rust installed, it is preferable to format with these options.
# (config file also used for GitHub actions)

edition = "2021"
unstable_features = true

use_field_init_shorthand = true
condense_wildcard_suffixes = true
format_macro_matchers = true
reorder_impl_items = true
group_imports = "StdExternalCrate"